// ===================================================================
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Jeff Nye, uarchlabs.com
// SPDX-FileCopyrightText: 2026 Jeff Nye <jeff@uarchlabs.com>
// ===================================================================
// FILE:    l1i_param_chk.sv
// DATE:    2026-10-01
// CONTACT: Jeff Nye
// -------------------------------------------------------------------
// L1I interface parameter agreement check (BP-115, TD#122 / TD-IF-1,
// ruled session-074).
//
// The IFU is hand written and reads bp_defines_pkg. The L1I is
// generated by cachegen and its constants are in l1i_pkg under
// cachegen's names. l1i_ifu_interfaces.md 3.1 lists the quantities
// the two sides share. This module makes them agree: any pair that
// differs raises $error at elaboration, so a lint of this module
// fails.
//
//   bp_defines_pkg      l1i_pkg
//   ---------------     -----------------
//   PA_WIDTH            L1iPaBits
//   L1I_LINE_BYTES      L1iLineBytes
//   L1I_LINE_BITS       L1iLineBits
//   L1I_OFFSET_BITS     L1iOffsetBits
//   REQ_ID_BITS         L1iReqIdBits
//   MAX_OUTSTANDING     L1iMaxOutstanding
//
// MAINT_FENCE_I and MAINT_CBO_INVAL are not compared. The emitted
// L1I has no maintenance port and l1i_pkg has no counterpart
// (TD#119).
//
// No ports and no logic. Lint only; it is never instantiated.
//
// Both packages are read by SCOPED reference. Neither is wildcard
// imported, so the module parameters below, which reuse the
// bp_defines_pkg names, shadow nothing.
//
// One parameter per compared quantity, each defaulting to the
// bp_defines_pkg value. The parameters exist so the check can be
// shown to fail: the Makefile's lint_neg target overrides PA_WIDTH
// with -G and requires the elaboration to fail with the PA_WIDTH
// message.
//
// Compared as int. l1i_pkg declares int unsigned and bp_defines_pkg
// declares int; the difference is expected and is not changed on
// either side. Every value here is small and positive, so the cast
// of the l1i_pkg side to int is exact.
// ===================================================================
module l1i_param_chk #(
  parameter int PA_WIDTH        = bp_defines_pkg::PA_WIDTH,
  parameter int L1I_LINE_BYTES  = bp_defines_pkg::L1I_LINE_BYTES,
  parameter int L1I_LINE_BITS   = bp_defines_pkg::L1I_LINE_BITS,
  parameter int L1I_OFFSET_BITS = bp_defines_pkg::L1I_OFFSET_BITS,
  parameter int REQ_ID_BITS     = bp_defines_pkg::REQ_ID_BITS,
  parameter int MAX_OUTSTANDING = bp_defines_pkg::MAX_OUTSTANDING
);

  // The l1i_pkg side, cast once to int.
  localparam int L1I_PA_BITS        = int'(l1i_pkg::L1iPaBits);
  localparam int L1I_LINE_BYTES_GEN = int'(l1i_pkg::L1iLineBytes);
  localparam int L1I_LINE_BITS_GEN  = int'(l1i_pkg::L1iLineBits);
  localparam int L1I_OFFSET_GEN     = int'(l1i_pkg::L1iOffsetBits);
  localparam int L1I_REQ_ID_GEN     = int'(l1i_pkg::L1iReqIdBits);
  localparam int L1I_MAX_OUT_GEN    = int'(l1i_pkg::L1iMaxOutstanding);

  if (PA_WIDTH != L1I_PA_BITS) begin : g_pa_width_mismatch
    $error("l1i_param_chk: PA_WIDTH = %0d differs from %s = %0d",
           PA_WIDTH, "l1i_pkg::L1iPaBits", L1I_PA_BITS);
  end

  if (L1I_LINE_BYTES != L1I_LINE_BYTES_GEN) begin : g_line_bytes_mismatch
    $error("l1i_param_chk: L1I_LINE_BYTES = %0d differs from %s = %0d",
           L1I_LINE_BYTES, "l1i_pkg::L1iLineBytes", L1I_LINE_BYTES_GEN);
  end

  if (L1I_LINE_BITS != L1I_LINE_BITS_GEN) begin : g_line_bits_mismatch
    $error("l1i_param_chk: L1I_LINE_BITS = %0d differs from %s = %0d",
           L1I_LINE_BITS, "l1i_pkg::L1iLineBits", L1I_LINE_BITS_GEN);
  end

  if (L1I_OFFSET_BITS != L1I_OFFSET_GEN) begin : g_offset_bits_mismatch
    $error("l1i_param_chk: L1I_OFFSET_BITS = %0d differs from %s = %0d",
           L1I_OFFSET_BITS, "l1i_pkg::L1iOffsetBits", L1I_OFFSET_GEN);
  end

  if (REQ_ID_BITS != L1I_REQ_ID_GEN) begin : g_req_id_bits_mismatch
    $error("l1i_param_chk: REQ_ID_BITS = %0d differs from %s = %0d",
           REQ_ID_BITS, "l1i_pkg::L1iReqIdBits", L1I_REQ_ID_GEN);
  end

  if (MAX_OUTSTANDING != L1I_MAX_OUT_GEN) begin : g_max_out_mismatch
    $error("l1i_param_chk: MAX_OUTSTANDING = %0d differs from %s = %0d",
           MAX_OUTSTANDING, "l1i_pkg::L1iMaxOutstanding", L1I_MAX_OUT_GEN);
  end

endmodule : l1i_param_chk
