#! /usr/bin/env bash

rm -f ho
echo "We are resuming a session for the RVA23 Co-Design" > ho
echo "which is part of RISC-V RVA23 Design"              >> ho
echo "" >> ho
echo "The basic flow was changed where the IA was allowed to modify" >> ho
echo "planning documents, we will cover this interactively. There" >> ho
echo "are results from this effort, however the context is large. " >> ho
# -------------------------------------------------------------
echo "" >> ho
echo "I have attached the following " >> ho
echo "- planning/PROJECT_CORE.md"     >> ho
echo "- planning/PROJECT_STATUS.md"   >> ho
echo "- CLAUDE.md"                    >> ho
echo "- templates/TASK_TEMPLATE.md"   >> ho
echo "All experiment files need to follow the task template exactly. " >> ho
echo "" >> ho
# -------------------------------------------------------------
echo "" >> ho
echo "The PA session hand off file path: " >> ho
echo "- pa_handoffs/session_handoff-$1.md"     >> ho
## -------------------------------------------------------------
echo "" >> ho
echo "The interactively created planning documents:" >> ho
echo "planning/arch/ftq_decisions.md"                >> ho
echo "planning/arch/ftq_entry_formats.md"            >> ho
echo "planning/interfaces/ftq_backend_interfaces.md" >> ho
echo "planning/interfaces/ftq_bpu_interfaces.md"     >> ho
echo "planning/interfaces/ftq_ifu_interfaces.md"     >> ho
## -------------------------------------------------------------
echo "" >> ho
echo "There are interactively created/completed task files: " >> ho
echo "BP-098 to BP-105. These can be included if necessary" >> ho
#echo "prompts/BP-098.md" >> ho
#echo "prompts/BP-099.md" >> ho
#echo "prompts/BP-100.md" >> ho
#echo "prompts/BP-101.md" >> ho
#echo "prompts/BP-102.md" >> ho
#echo "prompts/BP-103.md" >> ho
#echo "prompts/BP-104.md" >> ho
#echo "prompts/BP-105.md" >> ho
# -------------------------------------------------------------
echo "" >> ho
echo "There are transcripts from the IA interactive sessions" >> ho
echo "ia_export_session-004.txt and -005. These are large but can be" >> ho
echo "included if needed" >> ho
## -------------------------------------------------------------
echo "" >> ho
echo "There are handoffs generated by the IA for it's usage" >> ho
echo "ia_session_handoff-004.md and -005. These can be included" >> ho
echo "if needed" >> ho
#echo "ia_context/ia_handoffs/ia_session_handoff-004.md" >> ho
#echo "ia_context/ia_handoffs/ia_session_handoff-005.md" >> ho
# -------------------------------------------------------------
echo "" >> ho
cat planning/PROJECT_CORE.md          >> ho
cat planning/PROJECT_STATUS.md        >> ho
cat CLAUDE.md                         >> ho
cat templates/TASK_TEMPLATE.md        >> ho
cat pa_handoffs/session_handoff-$1.md >> ho
cat planning/arch/ftq_decisions.md                 >> ho
cat planning/arch/ftq_entry_formats.md             >> ho
cat planning/interfaces/ftq_backend_interfaces.md  >> ho
cat planning/interfaces/ftq_bpu_interfaces.md      >> ho
cat planning/interfaces/ftq_ifu_interfaces.md      >> ho

#cat prompts/BP-098.md >> ho
#cat prompts/BP-099.md >> ho
#cat prompts/BP-100.md >> ho
#cat prompts/BP-101.md >> ho
#cat prompts/BP-102.md >> ho
#cat prompts/BP-103.md >> ho
#cat prompts/BP-104.md >> ho
#cat prompts/BP-105.md >> ho

#cat ia_context/ia_exports/ia_export_session-004.txt  >> ho
#cat ia_context/ia_exports/ia_export_session-005.txt  >> ho

#cat ia_context/ia_handoffs/ia_session_handoff-004.md >> ho
#cat ia_context/ia_handoffs/ia_session_handoff-005.md >> ho
