#! /usr/bin/env bash

rm -f ho
echo "We are resuming a session for the RVA23 Co-Design" > ho
echo "which is part of RISC-V RVA23 Design"              >> ho
echo "" >> ho
echo "We will merge two separate context generation processes." >> ho
echo "This is your first task:" >> ho.
echo "There was a run with the PA which generated PROJECT_STATUS_INTERIM.md" >> ho
echo "There was a run with the IA which generated planning/PROJECT_STATUS.md" >> ho

echo "planning/PROJECT_STATUS.md is newer than PROJECT_STATUS_INTERIM.md" >>ho
echo "but there maybe information in PROJECT_STATUS_INTERIM.md that needs">>ho
echo "to be merged into planning/PROJECT_STATUS.md" >> ho.

echo "" >> ho
echo "The basic flow was changed where the IA was allowed to modify" >> ho
echo "planning documents, we will cover this interactively." >> ho

#echo "This context includes both a handoff created by" >> ho
#echo "the PA but also a set of files created interactively" >> ho
#echo "by the IA" >> ho
#echo "" >> ho
##echo "This context also includes task files generated by the IA" >> ho
##echo "" >> ho
#echo "NOTE: the context created by the IA was not known to the PA" >> ho
#echo "at the time it created it's handoff. The IA generated context" >> ho
#echo "should be considered newer than the session handoff from the PA" >> ho
# -------------------------------------------------------------
echo "" >> ho
echo "I have attached the following " >> ho
echo "- planning/PROJECT_CORE.md"     >> ho
echo "- planning/PROJECT_STATUS.md"   >> ho
echo "- PROJECT_STATUS_INTERIM.md"    >> ho
echo "- CLAUDE.md"                    >> ho
echo "- templates/TASK_TEMPLATE.md"   >> ho
echo "All experiment files need to follow the task template exactly. " >> ho
echo "" >> ho
echo "Note planning/PROJECT_STATUS.md was created by the IA and is   " >> ho
echo "newer than PROJECT_STATUS_INTERIM.md which was created" >> ho
echo "by the PA. These files need to be merged with primary source being" >> ho
echo "planning/PROJECT_STATUS.md annotated with any non-contradictory and" >> ho
echo "non-overlapping info from PROJECT_STATUS_INTERIM.md" >> ho

# -------------------------------------------------------------
echo "" >> ho
echo "The PA session hand off file name is: " >> ho
echo "- pa_handoffs/session_handoff-$1.md"     >> ho
## -------------------------------------------------------------
#echo "" >> ho
#echo "The interactively created task files are: " >> ho
#echo "prompts/BP-098.md" >> ho
#echo "prompts/BP-099.md" >> ho
#echo "prompts/BP-100.md" >> ho
#echo "prompts/BP-101.md" >> ho
#echo "prompts/BP-102.md" >> ho
#echo "prompts/BP-103.md" >> ho
#echo "prompts/BP-104.md" >> ho
#echo "prompts/BP-105.md" >> ho
## -------------------------------------------------------------
#echo "" >> ho
#echo "The transcripts from the interactive sessions are: " >> ho
#echo "ia_context/ia_exports/ia_export_session-004.txt" >> ho
#echo "ia_context/ia_exports/ia_export_session-005.txt" >> ho
## -------------------------------------------------------------
#echo "" >> ho
#echo "The handoffs generated by the IA for it's usage are: " >> ho
#echo "ia_context/ia_handoffs/ia_session_handoff-004.md" >> ho
#echo "ia_context/ia_handoffs/ia_session_handoff-005.md" >> ho
# -------------------------------------------------------------
echo "" >> ho
echo ":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::" >> ho
cat planning/PROJECT_CORE.md          >> ho
echo ":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::" >> ho
cat planning/PROJECT_STATUS.md        >> ho
echo ":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::" >> ho
cat PROJECT_STATUS_INTERIM.md         >> ho
echo ":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::" >> ho
cat CLAUDE.md                         >> ho
echo ":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::" >> ho
cat templates/TASK_TEMPLATE.md        >> ho
echo ":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::" >> ho
cat pa_handoffs/session_handoff-$1.md >> ho
#cat prompts/BP-098.md >> ho
#cat prompts/BP-099.md >> ho
#cat prompts/BP-100.md >> ho
#cat prompts/BP-101.md >> ho
#cat prompts/BP-102.md >> ho
#cat prompts/BP-103.md >> ho
#cat prompts/BP-104.md >> ho
#cat prompts/BP-105.md >> ho
#cat ia_context/ia_exports/ia_export_session-004.txt  >> ho
#cat ia_context/ia_exports/ia_export_session-005.txt  >> ho
#cat ia_context/ia_handoffs/ia_session_handoff-004.md >> ho
#cat ia_context/ia_handoffs/ia_session_handoff-005.md >> ho
